### ISSUE TITLE
Cannot update template files

### ISSUE THREAD

**Issue by mkinternet** [mplodowski/dynamicpdf-plugin#86] opened 2020-10-24 11:58 UTC
I cannot update template files when i edit template in plugins template editor. Templates made in created file are not seen.

Steps to reproduce error.

Create template in /plugins/myorg/myplugin/views/pdf/mytemplate.htm
Register template in /plugins/myorg/myplugin/Plugin.php using:

public function registerPDFTemplates()
{
	return [
		'myorg.myplugin::pdf.mytemplate',
	];
}	

Run template in a plugin
return \Renatio\DynamicPDF\Classes\PDF::loadTemplate('myorg.myplugin::pdf.mytemplate', $data)->stream();

Make changes in file /plugins/myorg/myplugin/views/pdf/mytemplate.htm. Chages are seen in generated pdf.
Open dynamicpdf plugin settings.
Choose created template.
Edit template and save it.

Make changes new in file /plugins/myorg/myplugin/views/pdf/mytemplate.htm. 

Chages NOT are seen in generated pdf.
I have to make changes in plugin settings. Changes made doesnt affect created template file so i have to make changes in file and in plugins settings

**Comment by mplodowski** [comment] 2020-11-19 17:59
This is by design. This works like October Mail templates and layouts.

Read more here: https://octobercms.com/docs/services/mail#mail-templates

So in summary when you update pdf template/layout in backend area, they are marked as customized and they will not be loaded from file view any more.

**Closed** 2020-11-22 17:36 UTC
Labels: Type: Unconfirmed Bug

**Comment by AllARTSoftworks** [comment] 2021-03-01 17:17
> I cannot update template files when i edit template in plugins template editor. Templates made in created file are not seen.
> 
> Steps to reproduce error.
> 
> Create template in /plugins/myorg/myplugin/views/pdf/mytemplate.htm
> Register template in /plugins/myorg/myplugin/Plugin.php using:
> 
> public function registerPDFTemplates()
> {
> return [
> 'myorg.myplugin::pdf.mytemplate',
> ];
> }
> 
> Run template in a plugin
> return \Renatio\DynamicPDF\Classes\PDF::loadTemplate('myorg.myplugin::pdf.mytemplate', $data)->stream();
> 
> Make changes in file /plugins/myorg/myplugin/views/pdf/mytemplate.htm. Chages are seen in generated pdf.
> Open dynamicpdf plugin settings.
> Choose created template.
> Edit template and save it.
> 
> Make changes new in file /plugins/myorg/myplugin/views/pdf/mytemplate.htm.
> 
> Chages NOT are seen in generated pdf.
> I have to make changes in plugin settings. Changes made doesnt affect created template file so i have to make changes in file and in plugins settings

If you press "Reset to default" in /backend/renatio/dynamicpdf/layouts/update/{id} files are loaded again from the filesystem.
